name       : python-filelock
version    : 3.12.2
release    : 15
source     :
    - https://pypi.io/packages/source/f/filelock/filelock-3.12.2.tar.gz : 002740518d8aa59a26b0c76e10fb8c6e15eae825d34b6fdf670333fd7b938d81
homepage   : https://github.com/tox-dev/py-filelock/
license    : Unlicense
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication.
builddeps  :
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pytest-mock
    - python-pytest-timeout
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
