name       : python-filelock
version    : 3.3.1
release    : 8
source     :
    - https://pypi.io/packages/source/f/filelock/filelock-3.3.1.tar.gz : 34a9f35f95c441e7b38209775d6e0337f9a3759f3565f6c5798f19618527c76f
license    : Unlicense
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication.
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs python-pytest-cov packaged
#    %python3_test pytest3
