name       : python-filelock
version    : 3.0.10
release    : 2
source     :
    - https://github.com/benediktschmitt/py-filelock/archive/v3.0.10.tar.gz : 1a6cb280fa2874c5ec540c708a07f05d4b71b6bdda4018394515340a4410a2b9
license    : Unlicense
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication:
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
