name       : python-filelock
version    : 3.3.2
release    : 10
source     :
    - https://pypi.io/packages/source/f/filelock/filelock-3.3.2.tar.gz : 7afc856f74fa7006a289fd10fa840e1eebd8bbff6bffb69c26c54a0512ea8cf8
homepage   : https://github.com/tox-dev/py-filelock/
license    : Unlicense
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication.
builddeps  :
    - python-pytest-cov
setup      : |
    sed -i '3 i\Version: %version%' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_ro'
