name       : python-filelock
version    : 3.7.1
release    : 13
source     :
    - https://pypi.io/packages/source/f/filelock/filelock-3.7.1.tar.gz : 3a0fd85166ad9dbab54c9aec96737b744106dc5f15c0b09a6744a445299fcf04
homepage   : https://github.com/tox-dev/py-filelock/
license    : Unlicense
component  : programming.python
summary    : A platform independent file lock for Python
description: |
    This package contains a single module, which implements a platform independent file lock in Python, which provides a simple way of inter-process communication.
builddeps  :
    - python-pytest-cov
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_ro'
